### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jgcmarins** [entria/font-generator#1]
Guys,

I've followed README instructions and after running `font-generator` command, the folder was created but I got this output:

```
TypeError: Cannot read property 'replace' of undefined
    at Template.generateSource (/usr/lib/node_modules/@entria/font-generator/node_modules/ejs/lib/ejs.js:573:24)
    at Template.compile (/usr/lib/node_modules/@entria/font-generator/node_modules/ejs/lib/ejs.js:483:12)
    at Object.compile (/usr/lib/node_modules/@entria/font-generator/node_modules/ejs/lib/ejs.js:338:16)
    at handleCache (/usr/lib/node_modules/@entria/font-generator/node_modules/ejs/lib/ejs.js:181:18)
    at Object.exports.render (/usr/lib/node_modules/@entria/font-generator/node_modules/ejs/lib/ejs.js:364:10)
    at /usr/lib/node_modules/@entria/font-generator/lib/runCLI.js:148:43
    at Array.map (native)
    at _callee$ (/usr/lib/node_modules/@entria/font-generator/lib/runCLI.js:147:31)
    at tryCatch (/usr/lib/node_modules/@entria/font-generator/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/@entria/font-generator/node_modules/regenerator-runtime/runtime.js:303:22)
```
Looking at `.ttf` file generated, I saw that the images aren't 100% built.

## EDIT
I've noticed that what was missing is this file `template/icons.platform.js.template`, with the following code:
```
const Icons = {
  <%_ for (item of props.items) { -%>
  <%- item.name %>: '\u<%- item.value %>',
  <%_ } -%>
};

export default Icons;
```
`font-generator` uses that file as a template, to generate `MyFont.android.js` and `MyFont.ios.js`

**Comment by nirpeled** [comment]
Where should this template/icons.platform.js.template file be saved at?
